name: Build Web & Dev Deploy

on:
  workflow_dispatch:

jobs:
  test:
    name: Test Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.1"
      - run: flutter pub get
      - run: flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/gen/translations -o locale_keys.g.dart
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: dart format $(find lib -name "*.dart" -not \( -name "*.*g.dart"  \) ) --set-exit-if-changed
  build_web:
    name: Build Flutter (Web)
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.1"
      - run: flutter pub get
      - run: flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/gen/translations -o locale_keys.g.dart
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build web -t lib/main_dev.dart
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:test-deprem-destek-org
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          PROJECT_ID: deprem-destek-org
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: web-build
          path: build/web
  deploy_web:
    name: Deploy Web to Firebase Hosting
    needs: build_web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: web-build
          path: web-build