name: PR Check

on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.1"
      - run: flutter pub get
      - run: flutter pub run easy_localization:generate -S assets/translations -f keys -O lib/gen/translations -o locale_keys.g.dart
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: dart format $(find lib -name "*.dart" -not \( -name "*.*g.dart"  \) ) --set-exit-if-changed
      - run: sh caret_check.sh
